wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1679905718.971937
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.14.0
      8:
      - 1
      - 5
architecture:
  desc: null
  value: HRNet
criterion:
  desc: null
  value: MSELoss
dataset:
  desc: null
  value: MIDV-500
heatmap_size:
  desc: null
  value:
  - 128
  - 128
image_size:
  desc: null
  value:
  - 512
  - 512
optimizer:
  desc: null
  value: Adam
test_dataloader_config:
  desc: null
  value:
    batch_size: 24
    shuffle: false
train_dataloader_config:
  desc: null
  value:
    batch_size: 24
    shuffle: true
training_config:
  desc: null
  value:
    epochs: 100
    gamma: 0.8
    lr: 0.001
    step_size: 5
